### ISSUE TITLE
ImportError::cannot import auth

### ISSUE THREAD

**Issue by regostar** [ClearBlade/ClearBlade-Python-SDK#7]
>>python BACnetAdapter.py

Traceback (most recent call last):
  File "BACnetAdapter.py", line 7, in <module>
    from MQTT import MQTT
  File "/home/pi/Documents/bacnet_adapter/BACnet-Adapter/MQTT.py", line 1, in <module>
    from clearblade import auth
ImportError: cannot import name auth

**Comment by ms1752** [comment]
Ah, I see the problem. The BACnet-Adapter expects v1 of the ClearBlade-Python-SDK, but the documentation links to the install instructions for v2.

I'd recommend uninstalling v2 with `pip uninstall clearblade`. Then you can follow the install instructions for v1 [here](https://github.com/ClearBlade/ClearBlade-Python-SDK/tree/v1.0).

I'll also update the BACnet-Adapter README with the correct link.

**Comment by regostar** [comment]
Thankyou
